### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gabriel-maxx** [Midi12/drv-loader#1]
what do i have to edit in the code so that when i run the exe it already loads the driver i want without needing to type arguments for ex: drv-loader.exe -o load -d Capcom Capcom.sys

**Comment by Midi12** [comment]
Hello @NightRaidGamer , you can write a batch file to achieve this. Kind regards, Midi

**Comment by gabriel-maxx** [comment]
> Hello @NightRaidGamer , you can write a batch file to achieve this. Kind regards, Midi

this I already know how to do, I'm learning and I would like to know how to do it in the c++ code itself without using external files
